var anims_file_transport = {
    "system": {
        "start":450,
        "end":510
    },
    "user": [
        {
            "steps": [
                {
                    "start":0,
                    "end":45,
                    "alpha":[],
                    "focus":[]
                },
                {
                    "start":46,
                    "end":110,
                    "alpha":["12_Grip_Module_Assembly",
                        "4_Slide",
                        "3_Rear_Sight",
                        "1_Front_Sight"],
                    "focus":[]
                },
                {
                    "start":111,
                    "end":155,
                    "alpha":["12_Grip_Module_Assembly",
                        "4_Slide",
                        "3_Rear_Sight",
                        "1_Front_Sight"],
                    "focus":["23_Trigger"]
                },
                {
                    "start":156,
                    "end":225,
                    "alpha":[],
                    "focus":["14_Magazine_Catch"]
                },
                {
                    "start":226,
                    "end":270,
                    "alpha":[],
                    "focus":[]
                },
                {
                    "start":271,
                    "end":350,
                    "alpha":[],
                    "focus":["21_Slide_Catch_Lever"]
                }
            ]
        },
        {
            "steps": [
                {
                    "start":0,
                    "end":5,
                    "alpha":[],
                    "focus":[]
                },
                {
                    "start":5,
                    "end":40,
                    "alpha":[
                        "12_Grip_Module_Assembly",
                        "04_Slide",
                        "03_Rear_Sight",
                        "01_Front_Sight"
                    ],
                    "focus":[]
                },
                {
                    "start":40,
                    "end":110,
                    "alpha":[
                        "12_Grip_Module_Assembly",
                        "04_Slide",
                        "03_Rear_Sight",
                        "01_Front_Sight"
                    ],
                    "focus":["23_Trigger"]
                },
                {
                    "start":110,
                    "end":112,
                    "alpha":[],
                    "focus":["14_Magazine_Catch"]
                },
                {
                    "start":112,
                    "end":114,
                    "alpha":[],
                    "focus":["21_Slide_Catch_Lever"]
                },
                {
                    "start":114,
                    "end":155,
                    "alpha":[],
                    "focus":[]
                },
                {
                    "start":156,
                    "end":210,
                    "alpha":[],
                    "focus":[]
                },
                {
                    "start":210,
                    "end":270,
                    "alpha":[],
                    "focus":[]
                },
                {
                    "start":270,
                    "end":319,
                    "alpha":[],
                    "focus":[]
                },
                {
                    "start":319,
                    "end":320,
                    "alpha":[],
                    "focus":[]
                }
            ]
        },
        {
            "steps": [
                {
                    "start":0,
                    "end":350,
                    "alpha":[],
                    "focus":[]
                },
            ]
        }
    ]
};
